"""Transfer of continuation ownership from a parent session to its successor.

There is exactly one ownership boundary. Before shutdown is confirmed the
parent owns continuation; while shutdown is requested neither session may
mutate; only TRANSFER_COMPLETE gives the successor ownership.
The parent Claude process is bound by tracing this process's real ancestry at
trigger time, re-proved immediately before it is signalled, and asked to exit
with a single SIGTERM. There is no SIGKILL path, no process-name matching, no
process-group signalling and no escalation: if anything cannot be proved, the
parent is left fully operational and the transfer is recorded as failed.
"""

from terminal_handoff.core import (  # noqa: F401
    PARENT_PROCESS_NAMES,
    PARENT_STOP_SIGNAL,
    PARENT_STOP_SIGNAL_NAME,
    TRANSFER_COMPLETE,
    TRANSFER_FAILED,
    TRANSFER_LAUNCHING,
    TRANSFER_OWNER,
    TRANSFER_PARENT_STOP_REQUESTED,
    TRANSFER_STATES,
    TRANSFER_SUCCESSOR_VERIFIED,
    TRANSFER_TRANSITIONS,
    SUCCESSOR_CHECK_NAMES,
    bind_parent_claude_process,
    bound_parent_process_present,
    bound_parent_process_state,
    build_transfer_record,
    acquire_supervisor_lease,
    claim_supervisor,
    evaluate_successor_checks,
    ensure_supervisor_running,
    heartbeat_timeout,
    parent_binding_path,
    process_ancestry,
    process_cwd,
    process_identity,
    process_exists,
    read_transfer,
    recover_parent_stop_requested,
    release_supervisor_lease,
    request_parent_stop,
    spawn_supervisor,
    stop_attempts,
    stop_grace_seconds,
    stop_parent_enabled,
    supervise_transfer,
    transfer_path,
    transfer_transition,
    update_transfer_fields,
    verify_parent_binding,
)

__all__ = [
    "PARENT_PROCESS_NAMES",
    "PARENT_STOP_SIGNAL",
    "PARENT_STOP_SIGNAL_NAME",
    "TRANSFER_COMPLETE",
    "TRANSFER_FAILED",
    "TRANSFER_LAUNCHING",
    "TRANSFER_OWNER",
    "TRANSFER_PARENT_STOP_REQUESTED",
    "TRANSFER_STATES",
    "TRANSFER_SUCCESSOR_VERIFIED",
    "TRANSFER_TRANSITIONS",
    "SUCCESSOR_CHECK_NAMES",
    "bind_parent_claude_process",
    "bound_parent_process_present",
    "bound_parent_process_state",
    "build_transfer_record",
    "acquire_supervisor_lease",
    "claim_supervisor",
    "evaluate_successor_checks",
    "ensure_supervisor_running",
    "heartbeat_timeout",
    "parent_binding_path",
    "process_ancestry",
    "process_cwd",
    "process_identity",
    "process_exists",
    "read_transfer",
    "recover_parent_stop_requested",
    "release_supervisor_lease",
    "request_parent_stop",
    "spawn_supervisor",
    "stop_attempts",
    "stop_grace_seconds",
    "stop_parent_enabled",
    "supervise_transfer",
    "transfer_path",
    "transfer_transition",
    "update_transfer_fields",
    "verify_parent_binding",
]
